### ISSUE TITLE
大写字母开头的snippets被过滤掉

### ISSUE THREAD

**Issue by yolo2h** [skywind3000/Leaderf-snippet#1]
我在使用Ultisnips，在添加大写字母开头的snippet后发现可以使用tab触发补全，但是不在leaderf-snippet列表中显示。

https://github.com/skywind3000/LeaderF-snippet/blob/7b5b496b5fd95d6a3626ab315fee020e2ff55714/plugin/leaderf_snippet.vim#L183

这里过滤掉大写字母开头的snippets是出于什么考量吗？能否添加全局变量使用户可以控制显示所有snippets？

**Comment by skywind3000** [comment]
大写字母里的 snippets 很多都是些 license，占用空间，分散注意力，不利于匹配。

**Comment by yolo2h** [comment]
好的，感谢您的回复。
